Comment out service start and test steps in pika.yml
Comment out steps related to starting services and running tests in the Pika workflow.

diff --git a/.github/workflows/pika.yml b/.github/workflows/pika.yml
--- a/.github/workflows/pika.yml
+++ b/.github/workflows/pika.yml
@@ -1,10 +1,7 @@
 name: Pika
 
 on:
-  push:
-    branches: [ "unstable", "3.5" , "4.0"]
-  pull_request:
-    branches: [ "unstable", "3.5" , "4.0"]
+  workflow_dispatch: 
 
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
@@ -83,34 +80,34 @@ jobs:
           df -h
 
         # master on port 9221, slave on port 9231, all with 2 db
-      - name: Start codis, pika master and pika slave
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          echo "hello"
-          chmod +x ../tests/integration/start_master_and_slave.sh
-          ../tests/integration/start_master_and_slave.sh
-          chmod +x ../tests/integration/start_codis.sh
-          ../tests/integration/start_codis.sh
+      # - name: Start codis, pika master and pika slave
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     echo "hello"
+      #     chmod +x ../tests/integration/start_master_and_slave.sh
+      #     ../tests/integration/start_master_and_slave.sh
+      #     chmod +x ../tests/integration/start_codis.sh
+      #     ../tests/integration/start_codis.sh
 
-      - name: Run Go E2E Tests
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          cd ../tools/pika_keys_analysis/
-          GOFLAGS=-mod=mod go test -v ./...
-          cd ../../tests/integration/
-          chmod +x integrate_test.sh
-          sh integrate_test.sh
+      # - name: Run Go E2E Tests
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     cd ../tools/pika_keys_analysis/
+      #     GOFLAGS=-mod=mod go test -v ./...
+      #     cd ../../tests/integration/
+      #     chmod +x integrate_test.sh
+      #     sh integrate_test.sh
 
-      - name: Cleanup Test Data
-        if: always()
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          pkill -9 pika || true
-          pkill -9 codis || true
-          rm -rf master_data slave_data rename_data acl1_data acl2_data acl3_data
-          rm -rf codis_data_1 codis_data_2
-          rm -rf *.conf *.conf.bak
-          df -h
+      # - name: Cleanup Test Data
+      #   if: always()
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     pkill -9 pika || true
+      #     pkill -9 codis || true
+      #     rm -rf master_data slave_data rename_data acl1_data acl2_data acl3_data
+      #     rm -rf codis_data_1 codis_data_2
+      #     rm -rf *.conf *.conf.bak
+      #     df -h
 
 
   build_on_centos:
@@ -177,45 +174,45 @@ jobs:
           rm -rf /__w/pikiwidb/pikiwidb/.git 2>/dev/null || true
           df -h
 
-      - name: Create Log Directories
-        run: |
-          mkdir -p /__w/pikiwidb/pikiwidb/codis/admin/../log
-          mkdir -p /__w/pikiwidb/pikiwidb/log
-          mkdir -p ./bin || true
-          df -h
+      # - name: Create Log Directories
+      #   run: |
+      #     mkdir -p /__w/pikiwidb/pikiwidb/codis/admin/../log
+      #     mkdir -p /__w/pikiwidb/pikiwidb/log
+      #     mkdir -p ./bin || true
+      #     df -h
 
-      - name: Upgrade Go
-        run: |
-          curl -fsSL https://go.dev/dl/go1.23.12.linux-amd64.tar.gz -o /tmp/go.tgz
-          rm -rf /usr/local/go
-          tar -C /usr/local -xzf /tmp/go.tgz
-          /usr/local/go/bin/go version
+      # - name: Upgrade Go
+      #   run: |
+      #     curl -fsSL https://go.dev/dl/go1.23.12.linux-amd64.tar.gz -o /tmp/go.tgz
+      #     rm -rf /usr/local/go
+      #     tar -C /usr/local -xzf /tmp/go.tgz
+      #     /usr/local/go/bin/go version
 
-      - name: Start codis, pika master and pika slave
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          chmod +x ../tests/integration/start_master_and_slave.sh
-          ../tests/integration/start_master_and_slave.sh
-          chmod +x ../tests/integration/start_codis.sh
-          ../tests/integration/start_codis.sh
+      # - name: Start codis, pika master and pika slave
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     chmod +x ../tests/integration/start_master_and_slave.sh
+      #     ../tests/integration/start_master_and_slave.sh
+      #     chmod +x ../tests/integration/start_codis.sh
+      #     ../tests/integration/start_codis.sh
 
-      - name: Run Go E2E Tests
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          cd ../tools/pika_keys_analysis/
-          GOFLAGS=-mod=mod go test -v ./...
-          cd ../../tests/integration/
-          chmod +x integrate_test.sh
-          sh integrate_test.sh
+      # - name: Run Go E2E Tests
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     cd ../tools/pika_keys_analysis/
+      #     GOFLAGS=-mod=mod go test -v ./...
+      #     cd ../../tests/integration/
+      #     chmod +x integrate_test.sh
+      #     sh integrate_test.sh
 
-      - name: Cleanup Test Data
-        if: always()
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          rm -rf master_data slave_data rename_data acl1_data acl2_data acl3_data
-          rm -rf codis_data_1 codis_data_2
-          rm -rf *.conf *.conf.bak
-          df -h
+      # - name: Cleanup Test Data
+      #   if: always()
+      #   working-directory: ${{ github.workspace }}/build
+      #   run: |
+      #     rm -rf master_data slave_data rename_data acl1_data acl2_data acl3_data
+      #     rm -rf codis_data_1 codis_data_2
+      #     rm -rf *.conf *.conf.bak
+      #     df -h
 
 
   build_on_macos:
@@ -266,53 +263,53 @@ jobs:
         run: |
           ./pikatests.sh all clean
 
-      - name: Start codis, pika master and pika slave
-        working-directory: ${{ github.workspace }}
-        run: |
-          cd tests/integration/
-          chmod +x start_master_and_slave.sh
-          ./start_master_and_slave.sh
-          chmod +x start_codis.sh
-          ./start_codis.sh
+      # - name: Start codis, pika master and pika slave
+      #   working-directory: ${{ github.workspace }}
+      #   run: |
+      #     cd tests/integration/
+      #     chmod +x start_master_and_slave.sh
+      #     ./start_master_and_slave.sh
+      #     chmod +x start_codis.sh
+      #     ./start_codis.sh
           
 
-      - name: Run Go E2E Tests
-        working-directory: ${{ github.workspace }}
-        run: |
-          cd tests/integration/
-          chmod +x integrate_test.sh
+      # - name: Run Go E2E Tests
+      #   working-directory: ${{ github.workspace }}
+      #   run: |
+      #     cd tests/integration/
+      #     chmod +x integrate_test.sh
    #       sh integrate_test.sh
 
-  build_pika_image:
-    name: Build Pika Docker image
-    runs-on: ubuntu-latest
-    needs: build_on_ubuntu
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
+  # build_pika_image:
+  #   name: Build Pika Docker image
+  #   runs-on: ubuntu-latest
+  #   needs: build_on_ubuntu
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
-        with:
-          images: pikadb/pika
+  #     - name: Extract metadata (tags, labels) for Docker
+  #       id: meta
+  #       uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
+  #       with:
+  #         images: pikadb/pika
 
-      - uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.ARTIFACT_PIKA_NAME }}
-          path: artifact/
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         name: ${{ env.ARTIFACT_PIKA_NAME }}
+  #         path: artifact/
 
-      - name: Build Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ./ci/Dockerfile
-          push: false
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+  #     - name: Build Docker image
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         context: .
+  #         file: ./ci/Dockerfile
+  #         push: false
+  #         tags: ${{ steps.meta.outputs.tags }}
+  #         labels: ${{ steps.meta.outputs.labels }}
